### ISSUE TITLE
Beautify Frontend - UI/UX (Front-end)

### ISSUE THREAD

**Issue by KHLocklin** [hightechu/hightechu-academy-victorianaloxonemap#10]
Use Bootstrap to Beautify Frontend.
Also add consistency throughout the project.

**Comment by beccap9** [comment]
This issue has been transferred to Mural. 
https://app.mural.co/t/hightechu8022/m/hightechu8022/1609804611296/601e129c9adb8771a6eac7a1838a038479ec9668
