### ISSUE TITLE
Edit/Remove Locations (Back-end)

### ISSUE THREAD

**Issue by LukeDomino** [hightechu/hightechu-academy-victorianaloxonemap#32]
Add Ability to Edit/Remove Locations.

PUT Request
DELETE Request

---

Show User only their Kit Locations? Add UserID to Kits Model?

**Comment by beccap9** [comment]
This issue has been transferred to Mural. https://app.mural.co/t/hightechu8022/m/hightechu8022/1609804611296/601e129c9adb8771a6eac7a1838a038479ec9668
