### ISSUE TITLE
Add Name Tags to the Kit Locations (Front-end)

### ISSUE THREAD

**Issue by FlyteWizard** [hightechu/hightechu-academy-victorianaloxonemap#40]
Get the name property for the GET Kits Location, and display on the Map as a Name Tag.

Something like this

```js
marker.bindPopup("<b>Hello world!</b><br>I am a popup.").openPopup();
```

but linked to the specific Kit Location Marker.

**Comment by beccap9** [comment]
This issue has been transferred to Mural. https://app.mural.co/t/hightechu8022/m/hightechu8022/1609804611296/601e129c9adb8771a6eac7a1838a038479ec9668
