### ISSUE TITLE
Routing Service - Shutdown

### ISSUE THREAD

**Issue by FlyteWizard** [hightechu/hightechu-academy-victorianaloxonemap#64]
The Routing Service we were using has been shutdown as of `March 9th 2020`.

More Information: https://github.com/Project-OSRM/osrm-backend/issues/5655

Routing now gives a CORS error: 

```
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://router.project-osrm.org/route/v1/walking/-123.3656,48…16057391?overview=false&alternatives=true&steps=true&hints=;. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.
```

which wasn't present before `March 9th 2020`.

**Comment by beccap9** [comment]
This issue has been transferred to Mural. https://app.mural.co/t/hightechu8022/m/hightechu8022/1609804611296/601e129c9adb8771a6eac7a1838a038479ec9668
